/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddGroup: typeof import('./components/nodeEdit/addGroup.vue')['default']
    AddNode: typeof import('./components/nodeEdit/addNode.vue')['default']
    LanguageSwitcher: typeof import('./components/LanguageSwitcher.vue')['default']
    MainConsole: typeof import('./components/index/mainConsole.vue')['default']
    MainDrawer: typeof import('./components/index/mainDrawer.vue')['default']
    NodeList: typeof import('./components/nodeEdit/nodeList.vue')['default']
    NodesFloatButton: typeof import('./components/nodeEdit/nodesFloatButton.vue')['default']
    NotificationProvider: typeof import('./components/notify/notificationProvider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spary: typeof import('./components/index/spary.vue')['default']
  }
}
